logging:
  level:
    root: info

spring:
  application:
    name: mail-services
  cloud:
    config:
      enabled: true
      fail-fast: true
      profile: default
  config:
    import: configserver:http://localhost:8888

server:
  port: 8001
  servlet:
    context-path: /mails

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: false
#    ip-address: 192.168.1.5
