spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://Users/czetsuya/Projects/SiriusACM/config-repo
server:
  error:
    whitelabel:
      enabled: true
  port: 8888
